using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using MotorPortal.Application.DTOs;
using MotorPortal.Application.Exceptions;
using MotorPortal.Application.Interfaces;
using MotorPortal.Domain.Constants;
using MotorPortal.Domain.Entities;
using MotorPortal.Infrastructure.Data;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace MotorPortal.Infrastructure.Services;

public class PolicyCertificateService : IPolicyCertificateService
{
    private readonly AppDbContext _context;
    private readonly IHostEnvironment _environment;
    private readonly ILogger<PolicyCertificateService> _logger;

    public PolicyCertificateService(AppDbContext context, IHostEnvironment environment, ILogger<PolicyCertificateService> logger)
    {
        _context = context;
        _environment = environment;
        _logger = logger;
    }

    private string CertificatesRoot => Path.Combine(_environment.ContentRootPath, "wwwroot", "certificates");

    public async Task<string> GenerateCertificateAsync(long policyId, CancellationToken cancellationToken = default)
    {
        var policy = await _context.PolicyMasters.AsNoTracking().FirstOrDefaultAsync(p => p.PolicyId == policyId, cancellationToken)
            ?? throw new NotFoundException($"Policy {policyId} not found.");

        var detail = await (
            from p in _context.ProposalMasters
            join d in _context.BatchDetails on p.DetailId equals d.DetailId
            where p.ProposalId == policy.ProposalId
            select d
        ).FirstOrDefaultAsync(cancellationToken);

        Directory.CreateDirectory(CertificatesRoot);
        var filePath = Path.Combine(CertificatesRoot, $"{policyId}.pdf");

        QuestPDF.Settings.License = LicenseType.Community;

        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Text("Motor Insurance Policy Certificate")
                    .SemiBold().FontSize(18).FontColor(Colors.Blue.Darken2);

                page.Content().PaddingVertical(20).Column(column =>
                {
                    column.Spacing(10);

                    void Row(string label, string value)
                    {
                        column.Item().Row(row =>
                        {
                            row.ConstantItem(180).Text(label).SemiBold();
                            row.RelativeItem().Text(value);
                        });
                    }

                    Row("Policy Number", policy.PolicyNo);
                    Row("Master Policy Number", detail?.MasterPolicyNo ?? "N/A");
                    Row("Make", policy.Make ?? "N/A");
                    Row("Model", policy.Model ?? "N/A");
                    Row("Engine Number", policy.EngineNo);
                    Row("Chassis Number", policy.ChassisNo);
                    Row("Premium", policy.Premium.ToString("N2"));
                    Row("Issued Date", policy.IssuedOn.ToString("yyyy-MM-dd"));
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by MotorPortal on ").FontSize(9);
                    text.Span(DateTime.UtcNow.ToString("u")).FontSize(9).SemiBold();
                });
            });
        }).GeneratePdf(filePath);

        var relativePath = $"/certificates/{policyId}.pdf";
        var existingCert = await _context.PolicyCertificates.FirstOrDefaultAsync(c => c.PolicyId == policyId, cancellationToken);
        if (existingCert is null)
        {
            _context.PolicyCertificates.Add(new PolicyCertificate
            {
                PolicyId = policyId,
                CertPath = relativePath,
                GeneratedOn = DateTime.UtcNow
            });
        }
        else
        {
            existingCert.CertPath = relativePath;
            existingCert.GeneratedOn = DateTime.UtcNow;
        }
        await _context.SaveChangesAsync(cancellationToken);

        _logger.LogInformation("Generated certificate for policy {PolicyId} at {Path}", policyId, filePath);

        return filePath;
    }

    public async Task<string> GetOrGenerateCertificatePathAsync(long policyId, CancellationToken cancellationToken = default)
    {
        var policyExists = await _context.PolicyMasters.AnyAsync(p => p.PolicyId == policyId, cancellationToken);
        if (!policyExists)
        {
            throw new NotFoundException($"Policy {policyId} not found.");
        }

        var cert = await _context.PolicyCertificates.AsNoTracking().FirstOrDefaultAsync(c => c.PolicyId == policyId, cancellationToken);
        if (cert is not null)
        {
            var existingPath = Path.Combine(_environment.ContentRootPath, "wwwroot", cert.CertPath.TrimStart('/').Replace("certificates/", "certificates" + Path.DirectorySeparatorChar));
            if (File.Exists(existingPath))
            {
                return existingPath;
            }
        }

        return await GenerateCertificateAsync(policyId, cancellationToken);
    }

    public async Task<BulkPrintResultDto> BulkPrintAsync(long batchId, long userId, CancellationToken cancellationToken = default)
    {
        var batch = await _context.BatchMasters.FirstOrDefaultAsync(b => b.BatchId == batchId, cancellationToken)
            ?? throw new NotFoundException($"Batch {batchId} not found.");

        var policies = await (
            from pm in _context.PolicyMasters
            join p in _context.ProposalMasters on pm.ProposalId equals p.ProposalId
            join d in _context.BatchDetails on p.DetailId equals d.DetailId
            where d.BatchId == batchId
            select pm
        ).ToListAsync(cancellationToken);

        if (policies.Count == 0)
        {
            throw new BusinessRuleException($"Batch {batchId} has no issued policies to print.");
        }

        var items = new List<BulkPrintItemDto>();
        foreach (var policy in policies)
        {
            await GenerateCertificateAsync(policy.PolicyId, cancellationToken);
            items.Add(new BulkPrintItemDto
            {
                PolicyId = policy.PolicyId,
                PolicyNo = policy.PolicyNo,
                CertPath = $"/certificates/{policy.PolicyId}.pdf"
            });
        }

        await BatchProcessingService.RunOrTranslateAsync(
            () => PgFunctions.AdvanceBatchStatusAsync(_context, batchId, BatchStatus.Printed, cancellationToken));

        _context.AuditLogs.Add(new AuditLog
        {
            UserId = userId,
            EntityName = "BATCH_MASTER",
            Action = "PRINT",
            RefId = batchId.ToString(),
            Timestamp = DateTime.UtcNow
        });
        await _context.SaveChangesAsync(cancellationToken);

        return new BulkPrintResultDto
        {
            BatchId = batchId,
            Status = BatchStatus.Printed,
            Certificates = items
        };
    }
}
